DROP FUNCTION IF EXISTS F_BIN_TO_UUID;
CREATE DEFINER=`otus`@`%` FUNCTION `F_BIN_TO_UUID`(bin BINARY(16)) RETURNS char(36) CHARSET utf8 COLLATE utf8_bin
    DETERMINISTIC
BEGIN
    DECLARE hex CHAR(32);
    SET hex = HEX(bin);
    RETURN LOWER(CONCAT(LEFT(hex, 8), '-', MID(hex, 9, 4), '-', MID(hex, 13, 4), '-', MID(hex, 17, 4), '-', RIGHT(hex, 12)));
END;

DROP FUNCTION IF EXISTS F_UUID_TO_BIN;
CREATE DEFINER=`otus`@`%` FUNCTION `F_UUID_TO_BIN`(uuid CHAR(36)) RETURNS binary(16)
    DETERMINISTIC
BEGIN
    RETURN UNHEX(CONCAT(REPLACE(uuid, '-', '')));
END;